---
#------------------------------------------------------------------------------
# Role: intersight-setup
# Default variables
#------------------------------------------------------------------------------

intersight:
  endpoint: intersight.com
  organization: default
  api_key_id: ""
  api_key_file: ""
  ssl_verify: true
