---
#------------------------------------------------------------------------------
# Role metadata for dnac-templates
#------------------------------------------------------------------------------

galaxy_info:
  author: EO Framework
  description: DNA Center policy templates and automation workflows
  company: EO Framework Solutions
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: GenericLinux
      versions:
        - all
  galaxy_tags:
    - cisco
    - dnac
    - networking
    - templates
    - policies

dependencies:
  - role: dnac-auth
