---
galaxy_info:
  author: EO Framework
  description: Configure Cisco ISE base settings
  company: Client Organization
  license: Proprietary
  min_ansible_version: "2.14"
  platforms:
    - name: GenericLinux
      versions:
        - all
  galaxy_tags:
    - cisco
    - ise
    - security
    - nac

dependencies: []
