---
#------------------------------------------------------------------------------
# Role metadata for dnac-auth
#------------------------------------------------------------------------------

galaxy_info:
  author: EO Framework
  description: DNA Center authentication and session management
  company: EO Framework Solutions
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: GenericLinux
      versions:
        - all
  galaxy_tags:
    - cisco
    - dnac
    - networking
    - authentication

dependencies: []
