---
#------------------------------------------------------------------------------
# Role metadata for dnac-assurance
#------------------------------------------------------------------------------

galaxy_info:
  author: EO Framework
  description: DNA Center Assurance and integrations configuration
  company: EO Framework Solutions
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: GenericLinux
      versions:
        - all
  galaxy_tags:
    - cisco
    - dnac
    - networking
    - assurance
    - integrations

dependencies:
  - role: dnac-auth
