---
galaxy_info:
  author: EO Framework
  description: Configure Cisco TrustSec SGTs and policies
  company: Client Organization
  license: Proprietary
  min_ansible_version: "2.14"
  platforms:
    - name: GenericLinux
      versions:
        - all
  galaxy_tags:
    - cisco
    - ise
    - trustsec
    - sgt

dependencies:
  - role: ise-policy
