---
galaxy_info:
  author: EO Framework
  description: Configure HyperFlex storage and datastores
  company: Client Organization
  license: Proprietary
  min_ansible_version: "2.14"
  platforms:
    - name: GenericLinux
      versions:
        - all
  galaxy_tags:
    - cisco
    - hyperflex
    - storage
    - vmware

dependencies:
  - role: vmware-integration
