---
galaxy_info:
  role_name: jenkins-setup
  author: EO Framework
  description: Configure Jenkins for Cisco network automation CI/CD
  company: Enterprise Orchestration
  license: proprietary
  min_ansible_version: "2.12"
  platforms:
    - name: Generic
      versions: [all]
  galaxy_tags:
    - jenkins
    - cicd
    - cisco
    - automation

dependencies: []
