---
# DR Inventory - Mist AI Network

all:
  vars:
    environment: dr
    solution_name: mist-ai-network
    solution_abbr: mist

  children:
    mist_cloud:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"

    juniper_switches:
      hosts:
        ex-switch-dr-01:
          ansible_host: "10.200.100.1"
          switch_role: distribution
      vars:
        ansible_network_os: junipernetworks.junos.junos
        ansible_connection: netconf

    access_switches:
      hosts: {}
