---
galaxy_info:
  author: EO Framework
  description: Configure ISE policies and network devices
  company: Client Organization
  license: Proprietary
  min_ansible_version: "2.14"
  platforms:
    - name: GenericLinux
      versions:
        - all
  galaxy_tags:
    - cisco
    - ise
    - policy
    - nac

dependencies:
  - role: ise-ad-integration
