---
#==============================================================================
# OpenShift Ansible Inventory - Production
#==============================================================================
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
  vars:
    env: prod
    kubeconfig: "{{ lookup('env', 'KUBECONFIG') | default('~/.kube/config') }}"
