---
galaxy_info:
  author: EO Framework
  description: Configure vSphere integration with HyperFlex
  company: Client Organization
  license: Proprietary
  min_ansible_version: "2.14"
  platforms:
    - name: GenericLinux
      versions:
        - all
  galaxy_tags:
    - cisco
    - hyperflex
    - vmware
    - vsphere

dependencies:
  - role: hyperflex-cluster
