---
#==============================================================================
# Ansible Collection Requirements
#==============================================================================
collections:
  - name: kubernetes.core
    version: ">=2.4.0"
  - name: redhat.openshift
    version: ">=2.3.0"
  - name: community.general
    version: ">=7.0.0"
  - name: ansible.utils
    version: ">=2.10.0"
