---
#------------------------------------------------------------------------------
# Role: ise-trustsec
# Default variables
#------------------------------------------------------------------------------

security_groups: []
security_group_acls: []
trustsec_matrix: []
