---
#==============================================================================
# OCP GitOps Role - Defaults
#==============================================================================

gitops:
  argocd_enabled: false
  argocd_repo_url: ""
  argocd_replicas: 2
